version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-data_pesanan}
      - DB_PORT=5432
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./views:/app/views
      - ./routes:/app/routes
      # Exclude node_modules from being overwritten
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "while ! nc -z db 5432; do sleep 2; done &&
      npm run dev"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-data_pesanan}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: