version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=data_pesanan
      - DB_PORT=5432
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: ["sh", "-c", "while ! nc -z db 5432; do sleep 2; done && npm start"]

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_pesanan
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
